server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/learning_platform?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  redis:
    host: localhost
    port: 6379
    database: 0

# JWT配置
jwt:
  secret: "secret_key"
  expiration: 3600000  # 1 hour
